// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {agent} from '../models';
import {config} from '../models';
import {serial} from '../models';

export function AgentApprove(arg1:string,arg2:string):Promise<void>;

export function AgentConnectMCP(arg1:main.MCPServerRequest):Promise<string>;

export function AgentDeleteMCPServer(arg1:string):Promise<void>;

export function AgentDisconnectMCP(arg1:string):Promise<void>;

export function AgentGetTask(arg1:string):Promise<agent.Task>;

export function AgentListMCPServers():Promise<string>;

export function AgentListTasks(arg1:string):Promise<string>;

export function AgentReject(arg1:string,arg2:string):Promise<void>;

export function AgentResume(arg1:string):Promise<string>;

export function AgentStart(arg1:agent.StartRequest):Promise<string>;

export function AgentStop(arg1:string):Promise<void>;

export function AssessAgentCommand(arg1:string):Promise<agent.PolicyDecision>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function ExportConfig():Promise<string>;

export function ExportConfigToFile():Promise<void>;

export function ImportConfig(arg1:string):Promise<void>;

export function ImportConfigFromFile():Promise<void>;

export function ImportKnownHostsFromFile():Promise<string>;

export function ImportOpenSSHConfigFromFile():Promise<string>;

export function ListConnections():Promise<string>;

export function ListGroups():Promise<string>;

export function LoadAIConfig():Promise<config.AIProviderConfig>;

export function LoadAIHistory():Promise<string>;

export function LoadDiagnostics():Promise<string>;

export function LoadSecurityConfig():Promise<agent.SecurityConfig>;

export function PortForwardList(arg1:string):Promise<string>;

export function PortForwardStart(arg1:main.PortForwardRequest):Promise<string>;

export function PortForwardStop(arg1:string):Promise<void>;

export function RAGAddDocument(arg1:main.RAGDocumentRequest):Promise<string>;

export function RAGDeleteDocument(arg1:string):Promise<void>;

export function RAGListDocuments():Promise<string>;

export function RAGReindex():Promise<number>;

export function RAGSearch(arg1:string):Promise<string>;

export function SFTPCancelTransfer(arg1:string):Promise<void>;

export function SFTPChmod(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SFTPDiskUsage(arg1:string,arg2:string):Promise<string>;

export function SFTPDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPExtensions(arg1:string):Promise<string>;

export function SFTPListDir(arg1:string,arg2:string):Promise<string>;

export function SFTPLocalHomeDir():Promise<string>;

export function SFTPLocalListDir(arg1:string):Promise<string>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPReadFile(arg1:string,arg2:string):Promise<string>;

export function SFTPRealPath(arg1:string,arg2:string):Promise<string>;

export function SFTPRemove(arg1:string,arg2:string):Promise<void>;

export function SFTPRemoveRecursive(arg1:string,arg2:string):Promise<void>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPSymlink(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPWriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SSHAppendSessionLogBase64(arg1:string,arg2:string):Promise<void>;

export function SSHConnect(arg1:main.ConnectRequest):Promise<string>;

export function SSHConnectByID(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SSHConnectByIDWithPassword(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function SSHDisconnect(arg1:string):Promise<void>;

export function SSHExecute(arg1:string,arg2:string):Promise<string>;

export function SSHKeyboardInteractiveResponse(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SSHListSessions():Promise<string>;

export function SSHRead(arg1:string):Promise<string>;

export function SSHReadSessionLog(arg1:string,arg2:number,arg3:number):Promise<main.sessionLogReadResult>;

export function SSHResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SSHTrustHostKey(arg1:string,arg2:string):Promise<void>;

export function SSHWrite(arg1:string,arg2:string):Promise<void>;

export function SSHWriteBase64(arg1:string,arg2:string):Promise<void>;

export function SaveAIConfig(arg1:config.AIProviderConfig):Promise<void>;

export function SaveAIHistory(arg1:string):Promise<void>;

export function SaveConnection(arg1:config.ConnectionRecord):Promise<void>;

export function SaveGroup(arg1:config.ConnectionGroup):Promise<void>;

export function SaveSecurityConfig(arg1:agent.SecurityConfig):Promise<void>;

export function SerialConnect(arg1:serial.Config):Promise<void>;

export function SerialDisconnect():Promise<void>;

export function SerialIsConnected():Promise<boolean>;

export function SerialListPorts():Promise<Array<string>>;

export function SerialRead(arg1:number):Promise<string>;

export function SerialWrite(arg1:string):Promise<number>;

export function SerialWriteBase64(arg1:string):Promise<number>;

export function SetConnectionGroup(arg1:string,arg2:string):Promise<void>;

export function SetConnectionTerminalTheme(arg1:string,arg2:string):Promise<void>;

export function SkillCheck(arg1:string):Promise<string>;

export function SkillDelete(arg1:string):Promise<void>;

export function SkillDocument(arg1:string):Promise<string>;

export function SkillEnable(arg1:string,arg2:boolean):Promise<void>;

export function SkillExportToFile(arg1:string):Promise<void>;

export function SkillGenerateSigningKey():Promise<string>;

export function SkillGet(arg1:string):Promise<string>;

export function SkillHistory(arg1:string):Promise<string>;

export function SkillImportFromFile():Promise<void>;

export function SkillList():Promise<string>;

export function SkillRestore(arg1:string,arg2:string):Promise<void>;

export function SkillRevokeKey(arg1:string):Promise<void>;

export function SkillRotateKey(arg1:string,arg2:string):Promise<void>;

export function SkillRun(arg1:agent.StartRequest):Promise<string>;

export function SkillSave(arg1:string):Promise<void>;

export function SkillSearch(arg1:string):Promise<string>;

export function SkillSign(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SkillTrustKey(arg1:string,arg2:string):Promise<void>;

export function TCPConnect(arg1:main.TCPConnectRequest):Promise<string>;

export function TCPDisconnect(arg1:string):Promise<void>;

export function TCPRead(arg1:string):Promise<string>;

export function TCPResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TCPWrite(arg1:string,arg2:string):Promise<void>;

export function TCPWriteBase64(arg1:string,arg2:string):Promise<void>;
