// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentApprove(arg1, arg2) {
  return window['go']['main']['App']['AgentApprove'](arg1, arg2);
}

export function AgentConnectMCP(arg1) {
  return window['go']['main']['App']['AgentConnectMCP'](arg1);
}

export function AgentDeleteMCPServer(arg1) {
  return window['go']['main']['App']['AgentDeleteMCPServer'](arg1);
}

export function AgentDisconnectMCP(arg1) {
  return window['go']['main']['App']['AgentDisconnectMCP'](arg1);
}

export function AgentGetTask(arg1) {
  return window['go']['main']['App']['AgentGetTask'](arg1);
}

export function AgentListMCPServers() {
  return window['go']['main']['App']['AgentListMCPServers']();
}

export function AgentListTasks(arg1) {
  return window['go']['main']['App']['AgentListTasks'](arg1);
}

export function AgentReject(arg1, arg2) {
  return window['go']['main']['App']['AgentReject'](arg1, arg2);
}

export function AgentResume(arg1) {
  return window['go']['main']['App']['AgentResume'](arg1);
}

export function AgentStart(arg1) {
  return window['go']['main']['App']['AgentStart'](arg1);
}

export function AgentStop(arg1) {
  return window['go']['main']['App']['AgentStop'](arg1);
}

export function AssessAgentCommand(arg1) {
  return window['go']['main']['App']['AssessAgentCommand'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function ExportConfigToFile() {
  return window['go']['main']['App']['ExportConfigToFile']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function ImportConfigFromFile() {
  return window['go']['main']['App']['ImportConfigFromFile']();
}

export function ImportKnownHostsFromFile() {
  return window['go']['main']['App']['ImportKnownHostsFromFile']();
}

export function ImportOpenSSHConfigFromFile() {
  return window['go']['main']['App']['ImportOpenSSHConfigFromFile']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function LoadAIConfig() {
  return window['go']['main']['App']['LoadAIConfig']();
}

export function LoadAIHistory() {
  return window['go']['main']['App']['LoadAIHistory']();
}

export function LoadDiagnostics() {
  return window['go']['main']['App']['LoadDiagnostics']();
}

export function LoadSecurityConfig() {
  return window['go']['main']['App']['LoadSecurityConfig']();
}

export function PortForwardList(arg1) {
  return window['go']['main']['App']['PortForwardList'](arg1);
}

export function PortForwardStart(arg1) {
  return window['go']['main']['App']['PortForwardStart'](arg1);
}

export function PortForwardStop(arg1) {
  return window['go']['main']['App']['PortForwardStop'](arg1);
}

export function RAGAddDocument(arg1) {
  return window['go']['main']['App']['RAGAddDocument'](arg1);
}

export function RAGDeleteDocument(arg1) {
  return window['go']['main']['App']['RAGDeleteDocument'](arg1);
}

export function RAGListDocuments() {
  return window['go']['main']['App']['RAGListDocuments']();
}

export function RAGReindex() {
  return window['go']['main']['App']['RAGReindex']();
}

export function RAGSearch(arg1) {
  return window['go']['main']['App']['RAGSearch'](arg1);
}

export function SFTPCancelTransfer(arg1) {
  return window['go']['main']['App']['SFTPCancelTransfer'](arg1);
}

export function SFTPChmod(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPChmod'](arg1, arg2, arg3);
}

export function SFTPDiskUsage(arg1, arg2) {
  return window['go']['main']['App']['SFTPDiskUsage'](arg1, arg2);
}

export function SFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2, arg3);
}

export function SFTPExtensions(arg1) {
  return window['go']['main']['App']['SFTPExtensions'](arg1);
}

export function SFTPListDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPListDir'](arg1, arg2);
}

export function SFTPLocalHomeDir() {
  return window['go']['main']['App']['SFTPLocalHomeDir']();
}

export function SFTPLocalListDir(arg1) {
  return window['go']['main']['App']['SFTPLocalListDir'](arg1);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPReadFile(arg1, arg2) {
  return window['go']['main']['App']['SFTPReadFile'](arg1, arg2);
}

export function SFTPRealPath(arg1, arg2) {
  return window['go']['main']['App']['SFTPRealPath'](arg1, arg2);
}

export function SFTPRemove(arg1, arg2) {
  return window['go']['main']['App']['SFTPRemove'](arg1, arg2);
}

export function SFTPRemoveRecursive(arg1, arg2) {
  return window['go']['main']['App']['SFTPRemoveRecursive'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPSymlink(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPSymlink'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2, arg3);
}

export function SFTPWriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPWriteFile'](arg1, arg2, arg3);
}

export function SSHAppendSessionLogBase64(arg1, arg2) {
  return window['go']['main']['App']['SSHAppendSessionLogBase64'](arg1, arg2);
}

export function SSHConnect(arg1) {
  return window['go']['main']['App']['SSHConnect'](arg1);
}

export function SSHConnectByID(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHConnectByID'](arg1, arg2, arg3);
}

export function SSHConnectByIDWithPassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SSHConnectByIDWithPassword'](arg1, arg2, arg3, arg4);
}

export function SSHDisconnect(arg1) {
  return window['go']['main']['App']['SSHDisconnect'](arg1);
}

export function SSHExecute(arg1, arg2) {
  return window['go']['main']['App']['SSHExecute'](arg1, arg2);
}

export function SSHKeyboardInteractiveResponse(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHKeyboardInteractiveResponse'](arg1, arg2, arg3);
}

export function SSHListSessions() {
  return window['go']['main']['App']['SSHListSessions']();
}

export function SSHRead(arg1) {
  return window['go']['main']['App']['SSHRead'](arg1);
}

export function SSHReadSessionLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHReadSessionLog'](arg1, arg2, arg3);
}

export function SSHResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHResize'](arg1, arg2, arg3);
}

export function SSHTrustHostKey(arg1, arg2) {
  return window['go']['main']['App']['SSHTrustHostKey'](arg1, arg2);
}

export function SSHWrite(arg1, arg2) {
  return window['go']['main']['App']['SSHWrite'](arg1, arg2);
}

export function SSHWriteBase64(arg1, arg2) {
  return window['go']['main']['App']['SSHWriteBase64'](arg1, arg2);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveAIHistory(arg1) {
  return window['go']['main']['App']['SaveAIHistory'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveGroup(arg1) {
  return window['go']['main']['App']['SaveGroup'](arg1);
}

export function SaveSecurityConfig(arg1) {
  return window['go']['main']['App']['SaveSecurityConfig'](arg1);
}

export function SerialConnect(arg1) {
  return window['go']['main']['App']['SerialConnect'](arg1);
}

export function SerialDisconnect() {
  return window['go']['main']['App']['SerialDisconnect']();
}

export function SerialIsConnected() {
  return window['go']['main']['App']['SerialIsConnected']();
}

export function SerialListPorts() {
  return window['go']['main']['App']['SerialListPorts']();
}

export function SerialRead(arg1) {
  return window['go']['main']['App']['SerialRead'](arg1);
}

export function SerialWrite(arg1) {
  return window['go']['main']['App']['SerialWrite'](arg1);
}

export function SerialWriteBase64(arg1) {
  return window['go']['main']['App']['SerialWriteBase64'](arg1);
}

export function SetConnectionGroup(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionGroup'](arg1, arg2);
}

export function SetConnectionTerminalTheme(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionTerminalTheme'](arg1, arg2);
}

export function SkillCheck(arg1) {
  return window['go']['main']['App']['SkillCheck'](arg1);
}

export function SkillDelete(arg1) {
  return window['go']['main']['App']['SkillDelete'](arg1);
}

export function SkillDocument(arg1) {
  return window['go']['main']['App']['SkillDocument'](arg1);
}

export function SkillEnable(arg1, arg2) {
  return window['go']['main']['App']['SkillEnable'](arg1, arg2);
}

export function SkillExportToFile(arg1) {
  return window['go']['main']['App']['SkillExportToFile'](arg1);
}

export function SkillGenerateSigningKey() {
  return window['go']['main']['App']['SkillGenerateSigningKey']();
}

export function SkillGet(arg1) {
  return window['go']['main']['App']['SkillGet'](arg1);
}

export function SkillHistory(arg1) {
  return window['go']['main']['App']['SkillHistory'](arg1);
}

export function SkillImportFromFile() {
  return window['go']['main']['App']['SkillImportFromFile']();
}

export function SkillList() {
  return window['go']['main']['App']['SkillList']();
}

export function SkillRestore(arg1, arg2) {
  return window['go']['main']['App']['SkillRestore'](arg1, arg2);
}

export function SkillRevokeKey(arg1) {
  return window['go']['main']['App']['SkillRevokeKey'](arg1);
}

export function SkillRotateKey(arg1, arg2) {
  return window['go']['main']['App']['SkillRotateKey'](arg1, arg2);
}

export function SkillRun(arg1) {
  return window['go']['main']['App']['SkillRun'](arg1);
}

export function SkillSave(arg1) {
  return window['go']['main']['App']['SkillSave'](arg1);
}

export function SkillSearch(arg1) {
  return window['go']['main']['App']['SkillSearch'](arg1);
}

export function SkillSign(arg1, arg2, arg3) {
  return window['go']['main']['App']['SkillSign'](arg1, arg2, arg3);
}

export function SkillTrustKey(arg1, arg2) {
  return window['go']['main']['App']['SkillTrustKey'](arg1, arg2);
}

export function TCPConnect(arg1) {
  return window['go']['main']['App']['TCPConnect'](arg1);
}

export function TCPDisconnect(arg1) {
  return window['go']['main']['App']['TCPDisconnect'](arg1);
}

export function TCPRead(arg1) {
  return window['go']['main']['App']['TCPRead'](arg1);
}

export function TCPResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TCPResize'](arg1, arg2, arg3);
}

export function TCPWrite(arg1, arg2) {
  return window['go']['main']['App']['TCPWrite'](arg1, arg2);
}

export function TCPWriteBase64(arg1, arg2) {
  return window['go']['main']['App']['TCPWriteBase64'](arg1, arg2);
}
